### ISSUE TITLE
What about android support? do i only need to add the detox runner for android or more installations?

### ISSUE THREAD

**Issue by royisch** [patniko/detox-appcenter#2]

**Comment by pniko** [comment]
Hi @royisch! Backlogged a bit, but will update this sample to show how you can accomplish the same thing in Android sometime next week.

**Comment by gusgard** [comment]
Hi, @pniko thanks for this repo!

Do you know if it is possible to test Detox with real devices (Android) in Appcenter?

When could we expect to have Detox by default in Appcenter?

Thanks!

**Comment by pniko** [comment]
Hi @gusgard, it's unfortunately not possible to test detox on real devices yet. It's something that would require considerable work on both the detox project and our current testing platform, but isn't outside the realm of possibility in the future. I have my eye on it.

**Comment by henrikra** [comment]
Are we able to run Detox tests in Appcenter with emulators? I don't really care about real devices until we have Android test running on emulators :)

**Comment by vonovak** [comment]
@patniko any progress on this? Having it work for android as well would be a huge time saver. Thanks!

**Comment by markymc** [comment]
@patniko I'd like to check if Android is working now. Did this get done? Thanks!

**Comment by pakkibokati2012** [comment]
@patniko I was wondering if the tests can be run on an android emulator. Do we have any script file?

**Comment by patniko** [comment]
Merged in Android support.
