### ISSUE TITLE
Update Detox version to enable testing Android & iOS builds on App Center

### ISSUE THREAD

**Issue by sebastianmalcolm** [patniko/detox-appcenter#26]
If this example is shown to successfully build & test for both Android & iOS, with a more recent version of Detox, then it should be easier to find more votes for officially supporting Detox as a testing framework in App Center's Test service. 
- **Add a Thumbs Up 👍 at: https://github.com/microsoft/appcenter/issues/262** 

I hope other people will help maintain this example until Detox is integrated into App Center's Test service.

**NOTE:** Updating Detox version should prevent some difficult to diagnose build failures for projects that use this repo as a starting point because the handling of keyboard input on iOS has been improved since this repo was last updated to verify using Detox 9.1.2 to run tests on App Center.

**Comment by mefjuu** [comment]
BTW. An URL from the script to retrieve applesimutils throws a 404:
https://raw.githubusercontent.com/wix/homebrew-brew/master/AppleSimulatorUtils-0.5.2.2.tar.gz

**Comment by leotm** [comment]
> BTW. An URL from the script to retrieve applesimutils throws a 404:
> https://raw.githubusercontent.com/wix/homebrew-brew/master/AppleSimulatorUtils-0.5.2.2.tar.gz

Try: https://github.com/wix/AppleSimulatorUtils/archive/0.7.2.tar.gz

Source: https://github.com/microsoft/appcenter/blob/master/sample-build-scripts/react-native/detox/appcenter-post-build.sh

**Comment by patniko** [comment]
Updated the repo with a [newer simpler version](https://github.com/patniko/detox-appcenter/blob/master/appcenter-pre-build.sh). Issues with brew on previous build agents forced the original workaround, but brew tap and install work correctly so you shouldn't have to worry about specifying a url anymore.

**Comment by MrDarkSkil** [comment]
If you want :) https://github.com/patniko/detox-appcenter/pull/32

**Comment by patniko** [comment]
Merged Android support. Thanks @MrDarkSkil !
